server:
  address: localhost
  port: 80
  servlet:
    context-path: /

spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.107.150.200:3306/yjw?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    name: root
    password: Root_12root
#   Thymeleaf 加载不出静态资源解决
  mvc:
    static-path-pattern: /static/**

mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
